version: "3"
    
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=webapp
      - MYSQL_USER=kazuki
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - "3306:3306"
    volumes:
      - ./initdb.d/sql:/docker-entrypoint-initdb.d
      - ./initdb.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./initdb.d/data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports: ["8888:80"]
    depends_on: ["mysql"]

  php:
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on: ["mysql"]
    build: ./php

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
    restart: always
    ports: ["8080:80"]
    depends_on: ["php"]